#!/usr/local/bin/php -f
<?

require_once("pkg-utils.inc");
$system_pkg_version  = get_system_pkg_version();

$current_installed_buildtime = trim(file_get_contents("/etc/version.buildtime"));

if ( $system_pkg_version['installed_version'] !== $system_pkg_version['version']) { 
    $additional_info = "WARNING - new version available\n" ;  $exitcode = 1; 
} else { 
    $additional_info = "OK - already at latest version\n" ; $exitcode = 0; 
}
$additional_info .= "Current version: ".$system_pkg_version['installed_version']."\n";
$additional_info .= "Built on: ".$current_installed_buildtime."\n";
$additional_info .= "Remote version: ".$system_pkg_version['version']."\n";

echo $additional_info;
exit ($exitcode);